-- Which session controls each seat, under which lease. Both rows exist from
-- the moment the assignment does. The lease is 256 random bits generated by
-- the server; it never leaves the server. `control_version` grows by one
-- with every change of holder or lease and is the compare-and-set token.
-- A deleted session leaves the seat with no controller.
CREATE TABLE game_seat_control (
  game_id                 text        NOT NULL,
  seat                    text        NOT NULL,
  controlling_session_id  uuid        NULL,
  control_lease_id        text        NOT NULL,
  control_version         bigint      NOT NULL,
  updated_at              timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT game_seat_control_pkey PRIMARY KEY (game_id, seat),
  CONSTRAINT game_seat_control_game_fkey
    FOREIGN KEY (game_id) REFERENCES game_assignments (game_id) ON DELETE CASCADE,
  CONSTRAINT game_seat_control_session_fkey
    FOREIGN KEY (controlling_session_id) REFERENCES user_sessions (session_id)
    ON DELETE SET NULL,
  CONSTRAINT game_seat_control_seat CHECK (seat IN ('white', 'black')),
  CONSTRAINT game_seat_control_lease_format CHECK (control_lease_id ~ '^[A-Za-z0-9_-]{43}$'),
  CONSTRAINT game_seat_control_lease_key UNIQUE (control_lease_id),
  CONSTRAINT game_seat_control_version CHECK (control_version >= 0)
);

-- The seats one session controls: logout, revocation, expiry.
CREATE INDEX game_seat_control_session_idx
  ON game_seat_control (controlling_session_id) WHERE controlling_session_id IS NOT NULL;
