declare const userIdBrand: unique symbol;

/**
 * The internal account key: a random (version 4) UUID in lowercase canonical
 * form, generated by the server. Never a username or an email address.
 */
export type UserId = string & { readonly [userIdBrand]: true };

const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export function isUserId(value: string): value is UserId {
  return UUID_V4.test(value);
}
